/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dNftSol from "./dNFT.sol";
export type { dNftSol };
export type { Bridge } from "./Bridge";
export type { DMarketPlace } from "./DMarketPlace";
export type { Lock } from "./Lock";
